[package]
name = "ops"
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { version = "1.0.57", features = ["std"] }
clap = { version = "3.2.1", features = ["derive"] }
colored = "2.0.0"
ctrlc = "3.2.3"
fancy-regex = "0.10.0"
lazy_static = "1.4.0"
path-absolutize = "3.0.14"
pathdiff = "0.2.1"
serde = "1.0.147"
serde_yaml = "0.9.14"
tempfile = "3.3.0"
toml = "0.5.9"
walkdir = "2.3.2"
