FROM $pre_build_service_image_tag as build

  $build

FROM debian:11-slim
  WORKDIR /app

  RUN apt-get update
  RUN apt-get -y install \
    ca-certificates \
    libpq5 \
    libssl-dev
  RUN rm -rf /var/lib/apt/lists/*

  $binary_copy

  $entrypoint
